import { Review } from './types';

export const reviews: Review[] = [
  {
    id: 'jb-001',
    source: 'Discord',
    username: 'dre_mf_',
    handle: '@dre_mf_',
    avatarUrl: 'https://picsum.photos/seed/101/48/48',
    rating: 5,
    content: 'july bypass W, gameloop 32 booted clean first try no bs',
    timestamp: '6/18/2026, 8:04:45 PM',
  },
  {
    id: 'jb-002',
    source: 'Discord',
    username: 'leocalliso',
    handle: '@leocalliso',
    avatarUrl: 'https://picsum.photos/seed/102/48/48',
    rating: 5,
    content: '+rep @July key landed in 30 sec, loader took 2 clicks. easiest bypass setup ive done',
    timestamp: '6/17/2026, 9:42:32 PM',
    proofUrl: '#',
  },
  {
    id: 'jb-003',
    source: 'Discord',
    username: 'trustedsellertb3',
    handle: '@trustedsellertb3',
    avatarUrl: 'https://picsum.photos/seed/103/48/48',
    rating: 5,
    content: 'support walked me thru vc++ + dx install then bypass fired up in 5 min. W team',
    timestamp: '6/16/2026, 8:07:07 PM',
  },
  {
    id: 'jb-004',
    source: 'Discord',
    username: 'rayphobia_',
    handle: '@rayphobia_',
    avatarUrl: 'https://picsum.photos/seed/104/48/48',
    rating: 5,
    content: '7 days straight on july bypass still UD. daily sessions no flag no ban 🔥',
    timestamp: '6/15/2026, 8:06:58 PM',
  },
  {
    id: 'jb-005',
    source: 'Discord',
    username: 'rayphobia_',
    handle: '@rayphobia_',
    avatarUrl: 'https://picsum.photos/seed/105/48/48',
    rating: 4,
    content: 'solid W, only -1 star bc i forgot to run as admin first time lol. bypass itself is UD af',
    timestamp: '6/14/2026, 1:23:10 AM',
  },
  {
    id: 'jb-006',
    source: 'Discord',
    username: 'wholelottanothing.',
    handle: '@wholelottanothing.',
    avatarUrl: 'https://picsum.photos/seed/106/48/48',
    rating: 5,
    content: 'tried 3 other bypasses before this. july actually stays up after updates. support responds faster than my ping',
    timestamp: '6/13/2026, 11:14:13 PM',
  },
  {
    id: 'jb-007',
    source: 'Discord',
    username: 'misconceptionns',
    handle: '@misconceptionns',
    avatarUrl: 'https://picsum.photos/seed/107/48/48',
    rating: 5,
    content: 'no fps tank no random crashes. july bypass runs lighter than the game itself somehow',
    timestamp: '6/12/2026, 4:07:25 AM',
  },
  {
    id: 'jb-008',
    source: 'Discord',
    username: 'arixo2310',
    handle: '@arixo2310',
    avatarUrl: 'https://picsum.photos/seed/108/48/48',
    rating: 5,
    content: 'legit +rep. key worked, loader injected, played all night — fully UD',
    timestamp: '6/11/2026, 1:44:51 AM',
  },
  {
    id: 'jb-009',
    source: 'Discord',
    username: 'riceboii24',
    handle: '@riceboii24',
    avatarUrl: 'https://picsum.photos/seed/109/48/48',
    rating: 5,
    content: 'bought the $0.15 trial to test, ended up grabbing a month same day. delivery instant',
    timestamp: '6/10/2026, 10:41:16 PM',
    proofUrl: '#',
  },
  {
    id: 'jb-010',
    source: 'Discord',
    username: 'z6ov',
    handle: '@z6ov',
    avatarUrl: 'https://picsum.photos/seed/110/48/48',
    rating: 5,
    content: '4 days on july bypass zero detections. main acc still clean',
    timestamp: '6/9/2026, 4:17:59 AM',
    proofUrl: '#',
  },
  {
    id: 'jb-011',
    source: 'Discord',
    username: 'f0x_mcloud',
    handle: '@f0x_mcloud',
    avatarUrl: 'https://picsum.photos/seed/111/48/48',
    rating: 5,
    content: '10/10 bypass. UD since day one, setup ~3 min with their download page. support answered in discord in under 2 min when loader threw an error. renewing sub fs',
    timestamp: '6/8/2026, 5:06:18 PM',
    proofUrl: '#',
  },
  {
    id: 'jb-012',
    source: 'Discord',
    username: 'dycexstormy',
    handle: '@dycexstormy',
    avatarUrl: 'https://picsum.photos/seed/112/48/48',
    rating: 5,
    content: '+rep July — bypass flawless, patch dropped same day ac updated. keys always legit never got scammed',
    timestamp: '6/7/2026, 8:46:29 PM',
  },
  {
    id: 'jb-013',
    source: 'Discord',
    username: 'braiden432112',
    handle: '@braiden432112',
    avatarUrl: 'https://picsum.photos/seed/113/48/48',
    rating: 5,
    content: 'july bypass on top. other sellers ghosted me, these guys actually fix ur shit',
    timestamp: '6/6/2026, 11:53:26 PM',
    proofUrl: '#',
  },
  {
    id: 'jb-014',
    source: 'Discord',
    username: 'missingmydma',
    handle: '@missingmydma',
    avatarUrl: 'https://picsum.photos/seed/114/48/48',
    rating: 5,
    content: 'broke my install at 2am, support fixed it same night. bypass back up in 10 min',
    timestamp: '6/5/2026, 9:19:49 PM',
  },
  {
    id: 'jb-015',
    source: 'Discord',
    username: 'pasha063500',
    handle: '@pasha063500',
    avatarUrl: 'https://picsum.photos/seed/115/48/48',
    rating: 5,
    content: 'july bypass goated. upgraded 1 week → 1 month. still UD, zero drama 🔥',
    timestamp: '6/4/2026, 6:14:57 PM',
  },
];