-- July Bypass — ключи 3 часа (plan_id: 3h)
-- Supabase → SQL Editor → Run
-- Повторный запуск безопасен: дубликаты по key пропускаются

insert into public.license_keys (key, plan_id) values
  ('Jule_6JBQQ_3HOURS', '3h'),
  ('Jule_3PIN8_3HOURS', '3h'),
  ('Jule_2RKRU_3HOURS', '3h'),
  ('Jule_32YR6_3HOURS', '3h'),
  ('Jule_GIIPE_3HOURS', '3h'),
  ('Jule_964U4_3HOURS', '3h'),
  ('Jule_1N8TR_3HOURS', '3h'),
  ('Jule_OF22A_3HOURS', '3h'),
  ('Jule_TKWVT_3HOURS', '3h'),
  ('Jule_SVRZM_3HOURS', '3h'),
  ('Jule_0MLTB_3HOURS', '3h'),
  ('Jule_0K4FL_3HOURS', '3h'),
  ('Jule_1CZIE_3HOURS', '3h'),
  ('Jule_07KZM_3HOURS', '3h'),
  ('Jule_OE3AL_3HOURS', '3h'),
  ('Jule_U5C5Q_3HOURS', '3h'),
  ('Jule_JHA1M_3HOURS', '3h'),
  ('Jule_QIKDE_3HOURS', '3h'),
  ('Jule_3ZV4Z_3HOURS', '3h'),
  ('Jule_JO2C5_3HOURS', '3h'),
  ('Jule_DVAWD_3HOURS', '3h'),
  ('Jule_T793E_3HOURS', '3h'),
  ('Jule_JMC29_3HOURS', '3h'),
  ('Jule_BTLBC_3HOURS', '3h'),
  ('Jule_Y37SZ_3HOURS', '3h'),
  ('Jule_I4Z6O_3HOURS', '3h'),
  ('Jule_K4C7K_3HOURS', '3h'),
  ('Jule_4KDEW_3HOURS', '3h'),
  ('Jule_UBEVK_3HOURS', '3h'),
  ('Jule_TT3NO_3HOURS', '3h'),
  ('Jule_174HV_3HOURS', '3h'),
  ('Jule_GEJGO_3HOURS', '3h'),
  ('Jule_5TJ0O_3HOURS', '3h'),
  ('Jule_U2FK3_3HOURS', '3h'),
  ('Jule_T0M1F_3HOURS', '3h'),
  ('Jule_PWNOP_3HOURS', '3h'),
  ('Jule_ZTHX9_3HOURS', '3h'),
  ('Jule_EHY9L_3HOURS', '3h'),
  ('Jule_AAIR3_3HOURS', '3h'),
  ('Jule_S1G4I_3HOURS', '3h'),
  ('Jule_RDYM4_3HOURS', '3h'),
  ('Jule_WPHY4_3HOURS', '3h'),
  ('Jule_7ZZEO_3HOURS', '3h'),
  ('Jule_Y4YSU_3HOURS', '3h'),
  ('Jule_LDSHG_3HOURS', '3h'),
  ('Jule_8Z4NQ_3HOURS', '3h'),
  ('Jule_07R60_3HOURS', '3h'),
  ('Jule_NZX6Q_3HOURS', '3h'),
  ('Jule_KDDAN_3HOURS', '3h'),
  ('Jule_I2O74_3HOURS', '3h'),
  ('Jule_4X9EY_3HOURS', '3h'),
  ('Jule_D6UQG_3HOURS', '3h'),
  ('Jule_W04FV_3HOURS', '3h'),
  ('Jule_NPU67_3HOURS', '3h'),
  ('Jule_ZGVTQ_3HOURS', '3h'),
  ('Jule_Q507F_3HOURS', '3h'),
  ('Jule_BRCQY_3HOURS', '3h'),
  ('Jule_20CHQ_3HOURS', '3h'),
  ('Jule_Y0K1Z_3HOURS', '3h'),
  ('Jule_X7B8K_3HOURS', '3h'),
  ('Jule_WFE82_3HOURS', '3h'),
  ('Jule_6SWTM_3HOURS', '3h'),
  ('Jule_1R54O_3HOURS', '3h'),
  ('Jule_E61ZT_3HOURS', '3h'),
  ('Jule_B0IMM_3HOURS', '3h'),
  ('Jule_57695_3HOURS', '3h'),
  ('Jule_6EY86_3HOURS', '3h'),
  ('Jule_SY6RN_3HOURS', '3h'),
  ('Jule_EZDLL_3HOURS', '3h'),
  ('Jule_OAOMH_3HOURS', '3h'),
  ('Jule_2GNBF_3HOURS', '3h'),
  ('Jule_L8NT3_3HOURS', '3h'),
  ('Jule_WOTYM_3HOURS', '3h'),
  ('Jule_VTHSL_3HOURS', '3h'),
  ('Jule_RTIUS_3HOURS', '3h'),
  ('Jule_7OX5P_3HOURS', '3h'),
  ('Jule_8S3PV_3HOURS', '3h'),
  ('Jule_4FSYR_3HOURS', '3h'),
  ('Jule_09KX3_3HOURS', '3h'),
  ('Jule_5X2KY_3HOURS', '3h'),
  ('Jule_MSP5H_3HOURS', '3h'),
  ('Jule_BKZKI_3HOURS', '3h'),
  ('Jule_BWYFC_3HOURS', '3h'),
  ('Jule_ZOAIY_3HOURS', '3h'),
  ('Jule_IWU1A_3HOURS', '3h'),
  ('Jule_H0MM4_3HOURS', '3h'),
  ('Jule_SP25L_3HOURS', '3h'),
  ('Jule_U7BV7_3HOURS', '3h'),
  ('Jule_ZP7AS_3HOURS', '3h'),
  ('Jule_PFTXW_3HOURS', '3h'),
  ('Jule_JH5J5_3HOURS', '3h'),
  ('Jule_VPSX7_3HOURS', '3h'),
  ('Jule_UYIU3_3HOURS', '3h'),
  ('Jule_BM0HQ_3HOURS', '3h'),
  ('Jule_B5TSR_3HOURS', '3h'),
  ('Jule_HR132_3HOURS', '3h'),
  ('Jule_Q8E7G_3HOURS', '3h'),
  ('Jule_L1DJ3_3HOURS', '3h'),
  ('Jule_0J1RA_3HOURS', '3h'),
  ('Jule_879B3_3HOURS', '3h')
on conflict (key) do nothing;

-- Проверка остатка
select plan_id, count(*) filter (where used = false) as free_keys, count(*) as total
from public.license_keys
group by plan_id
order by plan_id;